FROM golang:1.17-alpine as BUILDER

COPY . /go/src/transientdb
WORKDIR /go/src/transientdb

RUN apk add gcc musl-dev
RUN go build -tags=jsoniter .

FROM alpine:3.14

RUN mkdir -p /app/schemas && mkdir /app/data
COPY config.ini /app/.
COPY --from=BUILDER /go/src/transientdb/transientdb /app/transientdb
WORKDIR /app

ENTRYPOINT [ "/app/transientdb" ]

CMD [ ]